In [34]:
!pip3 install sklearn
!pip3 install matplotlib


In [31]:
import pandas as pd
import numpy as np

import os
import nltk
import pickle
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn import feature_extraction, linear_model, model_selection, preprocessing
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix
import string

In [26]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/fabricio/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
print(stopwords.words('portuguese'))

['de', 'a', 'o', 'que', 'e', 'é', 'do', 'da', 'em', 'um', 'para', 'com', 'não', 'uma', 'os', 'no', 'se', 'na', 'por', 'mais', 'as', 'dos', 'como', 'mas', 'ao', 'ele', 'das', 'à', 'seu', 'sua', 'ou', 'quando', 'muito', 'nos', 'já', 'eu', 'também', 'só', 'pelo', 'pela', 'até', 'isso', 'ela', 'entre', 'depois', 'sem', 'mesmo', 'aos', 'seus', 'quem', 'nas', 'me', 'esse', 'eles', 'você', 'essa', 'num', 'nem', 'suas', 'meu', 'às', 'minha', 'numa', 'pelos', 'elas', 'qual', 'nós', 'lhe', 'deles', 'essas', 'esses', 'pelas', 'este', 'dele', 'tu', 'te', 'vocês', 'vos', 'lhes', 'meus', 'minhas', 'teu', 'tua', 'teus', 'tuas', 'nosso', 'nossa', 'nossos', 'nossas', 'dela', 'delas', 'esta', 'estes', 'estas', 'aquele', 'aquela', 'aqueles', 'aquelas', 'isto', 'aquilo', 'estou', 'está', 'estamos', 'estão', 'estive', 'esteve', 'estivemos', 'estiveram', 'estava', 'estávamos', 'estavam', 'estivera', 'estivéramos', 'esteja', 'estejamos', 'estejam', 'estivesse', 'estivéssemos', 'estivessem', 'estiver', 'estiv

In [4]:
dataTRUE = "Data/size_normalized_texts/true/"

list = os.listdir(dataTRUE)
number_files_true = len(list)

In [5]:
dataFAKE = "Data/size_normalized_texts/fake/"

list = os.listdir(dataTRUE)
number_files_fake = len(list)

In [6]:
TEXT = []
LABEL = []

In [7]:
# Load data true
for i in range(number_files_true):
    title = list[i]
    LABEL.append(1)
    with open(dataTRUE + title,'r') as reader:

        doc = reader.read()
        doc.lower()
        doc.split()
        reader.close
        TEXT.append(doc)

In [8]:
# Load data fake
for i in range(number_files_fake):
    title = list[i]
    LABEL.append(0)
    with open(dataFAKE + title,'r') as reader:

        doc = reader.read()
        doc.lower()
        doc.split()
        reader.close
        TEXT.append(doc)

In [48]:
print(f"True {number_files_true}")
print(f"Fake {number_files_fake}")

True 3600
Fake 3600


In [9]:
assert len(TEXT) == len(LABEL)

In [10]:
print(f"Label {len(LABEL)} - TEXT {len(TEXT)}")

Label 7200 - TEXT 7200


In [12]:
def vectors_and_df(text, label):
    """
    creates vectors for the text files and returns dataframe with articles as word vectors 
    """
    
    cv = TfidfVectorizer()
    cv.fit(text)
    corpus_vecs = cv.transform(text)
    
    return pd.DataFrame(corpus_vecs.todense(), index=label, 
                        columns=cv.get_feature_names()), cv

In [13]:
# Store results into dataframe, keep cv for later prediction
df, cv = vectors_and_df(TEXT, LABEL)

/home/fabricio/.local/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [14]:
X = df
y = df.index

In [36]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30,shuffle=True, random_state=42)

In [37]:
model = LogisticRegression(max_iter=300)
model.fit(Xtrain, ytrain)

LogisticRegression(max_iter=300)

In [38]:

pred = model.predict(Xtest)
pred

array([1, 1, 0, ..., 0, 0, 1])

In [39]:
# Create the predictions for Y training data
preds = model.predict(Xtest)

print(model.score(Xtrain, ytrain))
print(f"Acuracia {model.score(Xtest, ytest)}")

0.964484126984127
Acuracia 0.8949074074074074


In [40]:
print("Accuracy:",round(metrics.accuracy_score(ytest, preds)*100, 2),'%')
print("Precision:",round(metrics.precision_score(ytest, preds)*100, 2), '%')

Accuracy: 89.49 %
Precision: 90.72 %


In [42]:
matrix = confusion_matrix(ytest, preds)
matrix

array([[975,  98],
       [129, 958]])

In [111]:
def predict(new_text):
    
    """
    Takes the pre-trained model pipeline and predicts new artist based on unseen text.
    
    Parameters
    ----------
    model : Trained scikit-learn model pipeline.
    new_text : str
    
    Returns
    ---------
    prediction : str
    
    """
    article = [new_text]
    # transform song into vector matrix
    new_article_vecs = cv.transform(article)
    ynew = new_article_vecs.todense()
    
    prediction = model.predict(ynew)
    
    return prediction[0]

In [112]:
TEXT = """A Câmara aprovou nesta quarta-feira, 4, o projeto de lei que cria um piso salarial para profissionais da enfermagem, a nível nacional, que varia de R$ 2.375 a R$ 4.750. O piso deve gerar um custo de até R$ 18 bilhões aos serviços de saúde públicos e privados de acordo com o presidente da Casa, deputado Arthur Lira (PP-AL). O texto foi aprovado por 449 votos favoráveis a 12, apesar de o governo Bolsonaro ter se posicionado contra.De origem do Senado, o PL determina que o piso da categoria deverá ser reajustado anualmente com base no Índice Nacional de Preços ao Consumidor (INPC). Além disso, fica assegurada a manutenção de salários eventualmente superiores ao valor inicial sugerido, independentemente da jornada de trabalho para a qual o profissional tenha sido contratado.Contudo, de acordo com a relatora da proposta, deputada Carmen Zanotto (Cidadania-SC), o projeto só irá à sanção presidencial após promulgação da Proposta de Emenda à Constituição (PEC) 122/15, aprovada em fevereiro deste ano, que proíbe a União de criar despesas aos demais entes federativos sem prever a transferência de recursos para o custeio.Desde segunda-feira, 2, profissionais da enfermagem circulavam pela Câmara e conversavam com parlamentares, numa mobilização que levou a um amplo apoio à proposta entre deputados. No plenário, parlamentares favoráveis ao projeto argumentaram que os profissionais de saúde merecem reconhecimento por terem estado na linha de frente do combate à pandemia de covid-19.O deputado Tiago Mitraud (MG), líder do Novo, único partido contrário ao piso, afirmou que a proposta é eleitoreira e tem alto impacto orçamentário. "Este projeto vai acabar com a saúde brasileira porque vamos ver as Santas Casas fechando, leitos de saúde fechando e os profissionais que hoje estão aqui lutando pelo piso desempregados porque os municípios não conseguirão pagar esse piso", criticou.Na avaliação do líder do governo na Câmara, deputado Ricardo Barros (PP-PR), a criação do piso representa um grande desafio para os cofres públicos. Barros disse que, como não havia indicação da origem dos recursos para custear a proposta, a orientação do governo seria contrária. "Neste momento, o projeto não atende à Lei de Responsabilidade Fiscal (LRF), e por isso o voto do governo é contrário", declarou.No entanto, como a aprovação do projeto era inevitável, Barros garantiu que o governo se manterá empenhado em buscar fontes de financiamento. "São R$ 16 bilhões que estão aguardando a fonte de recursos e nós estamos trabalhando demoradamente e insistentemente na busca de recursos para garantir que as conquistas sejam efetivas", disse.Os profissionais beneficiados pelo projeto são enfermeiros, técnicos em enfermagem e parteiras."""

In [113]:
TEXT2 =  """O ex-Secretário Nacional de Incentivo e Fomento à Cultura, André Porciúncula, revelou na manhã desta terça-feira (03) que a produtora Califórnia, da esposa de Daniela Mercury, recebeu incríveis R$ 1,8 milhões da Lei Rouanet em governos anteriores.A produtora Califórnia, da esposa da Daniela Mercury, recebeu 1,8 milhões da Rouanet dos governos antigos. Mas é claro que a Daniela está fazendo campanha para o ex-presidiário por puto amor ao Lula — escreveu Porciuncula, que também é ex-capitão da Polícia Militar da Bahia.Em outra postagem, o ex-secretário ainda revelou que o Instituto Sol da Liberdade, que pertence a cantora baiana, também recebeu 2,8 milhões da Lei Rouanet.Não é só a produtora da esposa da Daniela Mercury que lucrava milhões com a Lei Rouanet, o instituto que ela comanda costumava pegar milhões, antes do Governo Bolsonaro e as mudanças que fizemos na Rouanet. Sempre presuma uma teta vazia nos críticos do presidente — Porciuncula."""

In [114]:
predict(TEXT)

/home/fabricio/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/home/fabricio/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


1

In [49]:
# salvando modelo
with open('classifier_news', 'wb') as files:
    pickle.dump(model, files)

In [50]:
# load modelo
with open('classifier_news' , 'rb') as f:
    lr = pickle.load(f)

In [52]:
lr.predict(Xtest)

array([1, 1, 0, ..., 0, 0, 1])

In [30]:
def process_text(text):
    not_punc = [char for char in text if char not in  string.punctuation]
    not_punc = "".join(not_punc)
    
    clean_words = [word for word in not_punc.split() if word.lower() not in stopwords.words('portuguese') ]
    return clean_words

In [37]:
#process_text(TEXT)

In [115]:
classifier = MultinomialNB()
classifier.fit(Xtrain, ytrain)

MultinomialNB()

In [116]:
print(classifier.predict(Xtrain))
print(Xtrain.values)

[1 0 0 ... 1 1 1]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [45]:
from sklearn.metrics import classification_report

In [118]:
predic = classifier.predict(Xtrain)
print(classification_report(ytrain, predic))

              precision    recall  f1-score   support

           0       0.96      0.92      0.94      2525
           1       0.92      0.97      0.94      2515

    accuracy                           0.94      5040
   macro avg       0.94      0.94      0.94      5040
weighted avg       0.94      0.94      0.94      5040



In [119]:
predic = classifier.predict(Xtest)
print(classification_report(ytest, predic))

              precision    recall  f1-score   support

           0       0.88      0.82      0.85      1075
           1       0.83      0.89      0.86      1085

    accuracy                           0.86      2160
   macro avg       0.86      0.86      0.86      2160
weighted avg       0.86      0.86      0.86      2160



In [46]:
preds = model.predict(Xtrain)
print(classification_report(ytrain, preds))

              precision    recall  f1-score   support

           0       0.97      0.96      0.96      2527
           1       0.96      0.97      0.96      2513

    accuracy                           0.96      5040
   macro avg       0.96      0.96      0.96      5040
weighted avg       0.96      0.96      0.96      5040



In [47]:
preds = model.predict(Xtest)
print(classification_report(ytest, preds))

              precision    recall  f1-score   support

           0       0.88      0.91      0.90      1073
           1       0.91      0.88      0.89      1087

    accuracy                           0.89      2160
   macro avg       0.90      0.89      0.89      2160
weighted avg       0.90      0.89      0.89      2160



In [122]:
def predictNB(new_text):
    
    """
    Takes the pre-trained model pipeline and predicts new artist based on unseen text.
    
    Parameters
    ----------
    model : Trained scikit-learn model pipeline.
    new_text : str
    
    Returns
    ---------
    prediction : str
    
    """
    article = [new_text]
    # transform song into vector matrix
    new_article_vecs = cv.transform(article)
    ynew = new_article_vecs.todense()
    
    prediction = classifier.predict(ynew)
    
    return prediction[0]

In [124]:
predictNB(TEXT)

/home/fabricio/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(
/home/fabricio/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


1

### Cross Validation

In [134]:
model_LR = LogisticRegression(max_iter=300)

In [135]:
acuracias = cross_val_score(model_LR, X, y, cv=5, scoring="accuracy")
print("acuracias:", acuracias)
print("acuracia final:", np.mean(acuracias), "+-", np.std(acuracias))

acuracias: [0.91527778 0.88958333 0.92083333 0.91666667 0.90138889]
acuracia final: 0.9087499999999998 +- 0.011600340565456162


In [136]:
model_LR.fit(Xtrain, ytrain)

LogisticRegression(max_iter=300)

array([0.91527778, 0.88958333, 0.92083333, 0.91666667, 0.90138889])

In [130]:
acuracias.mean()

0.9087499999999998

In [131]:
acuracias_classifier = cross_val_score(classifier, X, y, cv=5, scoring="accuracy")

In [132]:
acuracias_classifier

array([0.87847222, 0.85763889, 0.86805556, 0.87569444, 0.85416667])

In [133]:
acuracias_classifier.mean()

0.8668055555555556

In [138]:
def predictNB(new_text):
    
    """
    Takes the pre-trained model pipeline and predicts new artist based on unseen text.
    
    Parameters
    ----------
    model : Trained scikit-learn model pipeline.
    new_text : str
    
    Returns
    ---------
    prediction : str
    
    """
    article = [new_text]
    # transform song into vector matrix
    new_article_vecs = cv.transform(article)
    ynew = new_article_vecs.todense()
    
    prediction = model_LR.predict(ynew)
    
    return prediction[0]

In [141]:
texto_uol = """O presidente do Senado, Rodrigo Pacheco (PSD-MG), derrubou uma tentativa de governistas de chamar o ministro Alexandre de Moraes, do Supremo Tribunal Federal (STF), para falar sobre os inquéritos que investigam atos antidemocráticos e o uso de fake news no plenário da Casa.O senador Eduardo Girão (Pode-CE) apresentou um requerimento para a realização de uma sessão de debates temáticos com Moraes, na tentativa de pressionar o ministro. O pedido recebeu apoio de governistas, aumentando as investidas do grupo contra Moraes diante dos ataques do presidente Jair Bolsonaro ao Judiciário. Pacheco impugnou o requerimento, impedindo a realização da audiência com o ministro.De acordo com o presidente do Senado, o pedido dos governistas contraria a Constituição e os propósitos previstos no regimento do Senado para a realização de debates temáticos, abrindo caminho para um "controle indireto de atos jurisdicionais" por meio de uma sessão com o magistrado. Girão recorreu da decisão de Pacheco. O presidente da Casa não julgou o recurso."""

In [144]:
predictNB(texto_uol)

/home/fabricio/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/home/fabricio/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


1